FROM microsoft/dotnet

ENV ASPNETCORE_URLS http://+:5000
EXPOSE 5000

# TODO: add the content to start the .net app:
# copy the content into place
# dotnet restore
# dotnet build
# let traffic flow in on port 5000
# dotnet run
