FROM microsoft/aspnetcore-build:2

ENV ASPNETCORE_URLS http://+:5000

# TODO: add the content to start the .net app:
# at build time:
# set the current directory
# copy the content into place
# `dotnet restore`
# `dotnet build`
# let traffic flow in on port 5000

# as the container starts:
# `dotnet run`
