FROM node

ENV NODE_ENV production
ENV PORT 3000

# TODO: add the content to start the Node app:
# at build time:
# set the current directory
# copy the manifest file: package.json
# `npm install`
# copy the content into place
# let traffic flow in on port 3000

# as the container starts:
# `npm start`
